apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  # Using LoadBalancer allows minikube tunnel to give it an external IP
  type: LoadBalancer
  selector:
    app: myapp
    color: blue # Initially points to blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
